EnergyPlus/urls.py
from django.conf.urls import url,include
from rest_framework import routers
from django.contrib import admin
from heatBalance import views
from project.views import model_form_upload,basic,helpView,UploadView,form_wizard_view,ProjectAutocomplete

#router=routers.DefaultRouter()
#router.register(r'heat',views.heatBalViewSet)

urlpatterns = [
    #url(r'^', include(router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^upload/$',UploadView.as_view(),name='upload'),
    url(r'^wizard/$',form_wizard_view,name="form_wizard_view"),
    url(r'^project/',include('project.urls')),
    url(r'^help/$',helpView.as_view(),name='help'),
    url(r'^ecm/',include('ecm.urls')),
    url(r'^project-autocomplete/$',ProjectAutocomplete.as_view(),name='project-autocomplete')
    #url(r'^project/$',ListView.as_view(),name='project'),
    #url(r'^project/(?P<pk>\d+)/$',DetailView.as_view(),name='detail'),
    #url(r'^project/(?P<pk>\d+)/basic$',basic.as_view(),name='basic'),
]

ecm/urls.py
from django.conf.urls import url,include
from rest_framework import routers
from django.contrib import admin
from heatBalance import views
from .views import ListView,DetailView

app_name="ecm"
urlpatterns = [
    url(r'^$', ListView.as_view(),name='index'),
    url(r'^(?P<pk>\d+)/$', DetailView.as_view(),name='detail'),
]

project/urls.py
from django.conf.urls import url,include
from django_filters.views import FilterView
from .filters import ProjectFilter
from rest_framework import routers
from django.contrib import admin
from heatBalance import views
from .views import model_form_upload,ListView,DetailView,basic,ProjectView,heatView,reportView,timeView,download_csv

app_name="project"
urlpatterns = [
    url(r'^$', ListView.as_view(),name='index'),
    url(r'^search/$', FilterView.as_view(filterset_class=ProjectFilter,template_name='search.html'),name='search'),
    url(r'^(?P<pk>\d+)/$',DetailView.as_view(),name='detail'),
    url(r'^(?P<pk>\d+)/basic$',basic.as_view(),name='basic'),
    url(r'^(?P<pk>\d+)/heat$',heatView.as_view(),name='heat'),
    url(r'^(?P<pk>\d+)/time$',timeView.as_view(),name='time'),
    url(r'^(?P<pk>[\w-]+)/$',ProjectView.as_view(),name='group'),
    url(r'^(?P<pk>\d+)/download$',download_csv,name='download'),
    url(r'^(?P<pk>[\w-]+)/report$',reportView.as_view(),name='report'),
]

heatBalance/models.py
from django.db import models

# Create your models here.
class heatBalance(models.Model):
	project=models.CharField(max_length=50)
	sensibleH=models.FloatField()
	sensibleC=models.FloatField()
	surfaceH=models.FloatField()
	surfaceC=models.FloatField()
	peopleH=models.FloatField()
	lightH=models.FloatField()
	equipH=models.FloatField()
	windowH=models.FloatField()
	transferH=models.FloatField()
	infiltrationH=models.FloatField()
	conductionH=models.FloatField()
	equipR=models.FloatField()
	windowR=models.FloatField()
	transferR=models.FloatField()
	infiltrationR=models.FloatField()
	conductionR=models.FloatField()

	class Meta:
		ordering=('project',)

project/models.py
from django.db import models
from ecm.models import ecm


def dir_path(instance, filename):
	return 'html/{0}/{1}'.format(instance.project, filename)

def epw_path(instance, filename):
	return 'epw/{0}'.format(filename)

# Create your models here.
class location(models.Model):
	name=models.CharField(max_length=50,blank=True)
	epw=models.FileField(upload_to=epw_path)

	def __str__(self):
		return self.name

class program(models.Model):
	program=models.CharField(max_length=30)

	def __str__(self):
		return self.program

class project(models.Model):
	project = models.CharField(max_length=50, blank=True)
	location=models.ForeignKey(location,related_name='project')
	program=models.ForeignKey(program,related_name='project')

	def __str__(self):
		return self.project

class scheme(models.Model):
	project=models.ForeignKey(project,related_name='schemes',on_delete=models.CASCADE)
	SCHEME_CHOICES = (
		('LEED_v3_baseline', 'LEED_v3_baseline'),
		('LEED_v4_baseline', 'LEED_v4_baseline'),
		('BEAM+_baseline', 'BEAM+_baseline'),
		('Proposed', 'Proposed')
	)
	scheme = models.CharField(max_length=30, choices=SCHEME_CHOICES, default='BEAM+_baseline')
	configuration=models.TextField()
	ecms = models.ManyToManyField(ecm, blank=True)

	def __str__(self):
		return str(self.project)+"_"+self.scheme

class html(models.Model):
	scheme=models.ForeignKey(scheme,related_name='html',on_delete=models.CASCADE)
	version = models.IntegerField(default=0)
	diff = models.TextField(blank=True)
	html = models.FileField(upload_to=dir_path)
	uploaded_at = models.DateTimeField(auto_now_add=True)

	#def __str__(self):
	#	return self.scheme+"_v"+str(self.version)


class area(models.Model):
	html = models.OneToOneField(html, primary_key=True, on_delete=models.CASCADE)
	total_area = models.IntegerField()
	condition_area = models.IntegerField()
	uncondition_area = models.IntegerField()


class unmet(models.Model):
	html = models.OneToOneField(html, primary_key=True, on_delete=models.CASCADE)
	heating = models.FloatField()
	cooling = models.FloatField()
	ashrae = models.FloatField()


class wwr(models.Model):
	html = models.OneToOneField(html, primary_key=True, on_delete=models.CASCADE)
	total = models.FloatField()
	north = models.FloatField()
	east = models.FloatField()
	south = models.FloatField()
	west = models.FloatField()


class energy(models.Model):
	html = models.OneToOneField(html, primary_key=True, on_delete=models.CASCADE)
	total = models.FloatField()
	euipertotal = models.FloatField()
	euipercondition = models.FloatField()


class loc(models.Model):
	html = models.OneToOneField(html, primary_key=True, on_delete=models.CASCADE)
	cooling=models.CharField(max_length=100, default='test')
	eui=models.CharField(max_length=100, default='test')
	euicon=models.CharField(max_length=100, default='test')
	energy=models.CharField(max_length=100, default='test')
	fan=models.CharField(max_length=100, default='test')
	glass=models.CharField(max_length=100, default='test')
	heatbal=models.CharField(max_length=100, default='test')
	hvac=models.CharField(max_length=100, default='test')
	hw=models.CharField(max_length=100, default='test')
	light=models.CharField(max_length=100, default='test')
	oa=models.CharField(max_length=100, default='test')
	oamin=models.CharField(max_length=100, default='test')
	opaque=models.CharField(max_length=100, default='test')
	pump=models.CharField(max_length=100, default='test')
	unmet=models.CharField(max_length=100, default='test')
	wwr=models.CharField(max_length=100, default='test')
	wwrcon=models.CharField(max_length=100, default='test')
	zone = models.CharField(max_length=100, default='test')


class electricity(models.Model):
	html = models.OneToOneField(html, primary_key=True)
	file = models.FileField(upload_to='electricity')

project/forms.py
from django.forms import ModelForm, inlineformset_factory
from project.models import html,scheme,project
from django.forms import widgets
from django import forms
from dal import autocomplete

class DocumentForm(ModelForm):
    class Meta:
        model = html
        exclude=()

class SchemeForm(ModelForm):
    class Meta:
        model=scheme
        exclude=['configuration','ecms']

htmlFormSet=inlineformset_factory(project,
                                  scheme,
                                  extra=1,
                                  can_delete=False,
                                  form=SchemeForm)

class ProjectForm(ModelForm):
    #location=forms.ModelChoiceField(queryset=project.objects.all(),widget=autocomplete.ModelSelect2(url='project-autocomplete'))
    class Meta:
        model=project
        exclude=()

heatBalance/views.py
from django.shortcuts import render
from heatBalance.models import heatBalance
from heatBalance.serializer import heatBalSerializer
from rest_framework import viewsets

# Create your views here.
class heatBalViewSet(viewsets.ModelViewSet):
	queryset = heatBalance.objects.all()
	serializer_class=heatBalSerializer

project/views.py
from django.shortcuts import render,get_object_or_404
from project.models import html, area, unmet, wwr, energy, loc,scheme,project
from project.forms import DocumentForm,htmlFormSet,SchemeForm,ProjectForm
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import CreateView
from libs.EPprocessing.main import ProcessHtml
# from EnergyPlus import settings
from django.core.files import File
import os
import pandas
from django.conf import settings
from django.core.urlresolvers import reverse
from io import BytesIO
import zipfile
from io import StringIO
from django.db import transaction
from formtools.wizard.views import SessionWizardView
from django.core.files.storage import FileSystemStorage
from dal import autocomplete
import inspect

# Create your views here.
class ListView(ListView):
    model = html
    # queryset=html.objects.all()
    # print(queryset)
    template_name = 'project_list.html'

class DetailView(DetailView):
    model = html
    template_name = 'project_detail.html'

    def makepath(self, data, strcsv):
        abspath = str(os.path.join((os.path.dirname(data["object"].html.path)), strcsv))
        strpath = abspath[len(settings.MEDIA_ROOT):].replace("\\", "/")
        return strpath

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        strpath1 = self.makepath(data, "Zone.csv")
        data["zone"] = "../../static" + strpath1
        print(self.object.ecms.all())
        data['ecms']=self.object.ecms.all()
        print(data['ecms'])
        return data


class ProjectView(ListView):
    #queryset=html.objects.all()
    model=html
    template_name = 'project_group.html'
    def get_queryset(self):
        qs=super(ProjectView,self).get_queryset()
        return qs.filter(project=self.kwargs['pk'])


class basic(DetailView):
    template_name = 'basic_info.html'

class heatView(DetailView):
    template_name = 'heat_balance.html'

class reportView(DetailView):
    template_name = 'report.html'

class timeView(ListView):
    template_name="timeseries.html"

class helpView(ListView):
    template_name="help.html"

def download_csv(request,pk):
    #query the data we want to download
    obj=html.objects.get(pk=pk)
    loc=obj.loc
    fields=loc._meta.get_fields()
    filenames=[]
    for f in fields:
        csvpath=getattr(loc, f.name)
        if str(csvpath).endswith("csv"):
            filenames.append(csvpath)

    print(filenames[0])
    zip_subdir = "result_csv"
    zip_filename = "%s.zip" % zip_subdir

    s=StringIO()
    b=BytesIO()
    zf = zipfile.ZipFile(b, 'w')

    for fpath in filenames:
        fdir,fname=os.path.split(fpath)
        zip_path=os.path.join(zip_subdir,fname)
        #print(zip_path)

        fpath1=fpath[6:].replace("static","data")
        zf.write(fpath1)
    zf.close()

    response=HttpResponse(b.getvalue(),content_type = "application/x-zip-compressed")
    response['Content-Disposition'] = 'attachment; filename=%s' % zip_filename

    return response

def UploadFunction(request):
    form=Wizard.as_view([Form1,Form2])

"""
#This can be used if I can combine wizard and inline form
TRANSFER_FORMS = [
    ("step1", htmlFormSet),
    ("step2", DocumentForm),
]
TRANSFER_TEMPLATES = {
    "step1":'scheme_form.html',
    "step2":"upload2.html",
}

class Wizard(SessionWizardView):
    location=os.path.join(settings.MEDIA_ROOT,'data','temp')
    print (location)
    file_storage = FileSystemStorage(location)

    def get_template_names(self):
        return [TRANSFER_TEMPLATES[self.steps.current]]

    def done(self, form_list, **kwargs):
        print(form_list[0])
        print(form_list[1])
        upload_file=form_list[0].cleaned_data('my_file')
        self.file_storage.delete(upload_file.name)

form_wizard_view = Wizard.as_view(TRANSFER_FORMS)
"""
TRANSFER_FORMS = [
    ("step1", ProjectForm),
    ("step2", SchemeForm),
    ("step3", DocumentForm),
]
TRANSFER_TEMPLATES = {
    "step1":"upload2.html",
    "step2":"upload2.html",
    "step3":"upload2.html"
}

class UploadWizard(SessionWizardView):
    location=os.path.join(settings.MEDIA_ROOT,'data','temp')
    print (location)
    file_storage = FileSystemStorage(location)


    def get_template_names(self):
        return [TRANSFER_TEMPLATES[self.steps.current]]

    def get_form_initial(self, step):
        initial={}
        if step == 'step3':
            temp1=self.storage.get_step_data('step1')
            temp2=self.storage.get_step_data('step2')
            print(temp1)
            print (temp2)
            project_name=temp1.get('step1-project')
            project_id=temp2.get('step2-project')
            scheme_name = temp2.get('step2-scheme')
            #print(project,scheme)
            #s=scheme(project=project_name)
            #print(s)
            test = scheme.objects.filter(scheme=scheme_name, project_id=project_id)
            #test2=html.objects.filter(scheme__scheme=scheme_name,scheme_project=project_name)
            #print(test)
            #print(test.values())
            #according to the queryset based on the temp1,2,set initial data
            #initial['version']=

    def done(self, form_list, **kwargs):
        print(form_list[0])
        print(form_list[1])
        print(form_list[2])
        upload_file=form_list[0].cleaned_data('my_file')
        self.file_storage.delete(upload_file.name)

        return HttpResponseRedirect(reverse('project:index'))


inspect.getmembers(UploadWizard)
form_wizard_view = UploadWizard.as_view(TRANSFER_FORMS)

class UploadView(CreateView):
    model = project
    fields = ['project','location','program']
    template_name = 'scheme_form.html'
    #success_url = reverse('project:index')

    def get_context_data(self,**kwargs):
        data = super(UploadView,self).get_context_data(**kwargs)
        if self.request.POST:
            data['schemes'] = htmlFormSet(self.request.POST)

        else:
            data['schemes']=htmlFormSet()

        print(data['schemes'])
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        schemes = context['schemes']
        with transaction.atomic():
            self.object = form.save()

            if schemes.is_valid():
                schemes.instance = self.object
                schemes.save()
            return super(UploadView,self).form_valid(form)


def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        print (form)
        if form.is_valid():
            newhtml = form.save()
            # newDoc=html(html=request.FILES['html'])
            newhtml.save()

            queryset = html.objects.all().last()
            dest = os.path.dirname(queryset.html.path)+str(queryset.version)

            db = process_html(queryset.html.path, dest)

            register_area(db["Area"], area, newhtml)
            register_unmet(db["Unmet"], unmet, newhtml)
            register_wwr(db["WWR"], wwr, newhtml)
            register_ene(db["EUI"], energy, newhtml)

            #root=dest+"\\"
            root="../../static"+dest[len(settings.MEDIA_ROOT):].replace("\\", "/")+"/"
            print("directory:"+root)
            colList=["Cooling","ELUI","ELUIcon","Energy","Fan","Glass","HeatBalance","HVAC","HW","Light","OAaverage","OAmin","Opaque","Pump","UnmetDetail","WWR","WWRcon","Zone"]
            ext=".csv"
            register_loc(root,ext,colList,loc,newhtml)

            return HttpResponseRedirect(reverse('project:index'))
    else:
        form = DocumentForm()

    return render(request, 'model_form_upload.html', {'form': form})
    documents = html.objects.all()

class ProjectAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = project.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

def register_loc(r,e,l,strDB,parentDB):
    db=strDB(html=parentDB,cooling=r+l[0]+e,eui=r+l[1]+e,euicon=r+l[2]+e,energy=r+l[3]+e,fan=r+l[4]+e,glass=r+l[5]+e,heatbal=r+l[6]+e,hvac=r+l[7]+e,hw=r+l[8]+e,light=r+l[9]+e,oa=r+l[10]+e,oamin=r+l[11]+e,opaque=r+l[12]+e,pump=r+l[13]+e,unmet=r+l[14]+e,wwr=r+l[15]+e,wwrcon=r+l[16]+e,zone=r+l[17]+e)
    db.save()


def register_area(df, strDB, parentDB):
    db = strDB(html=parentDB, total_area=df.iloc[1, 1], condition_area=df.iloc[2, 1], uncondition_area=df.iloc[3, 1])
    db.save()


def register_unmet(df, strDB, parentDB):
    db = strDB(html=parentDB, heating=df.iloc[1, 1], cooling=df.iloc[2, 1], ashrae=df.iloc[3, 1])
    db.save()


def register_wwr(df, strDB, parentDB):
    print(df.iloc[5, 0])
    db = strDB(html=parentDB, total=df.iloc[5, 1], north=df.iloc[5, 2], east=df.iloc[5, 3], south=df.iloc[5, 4],
               west=df.iloc[5, 5])
    db.save()


def register_ene(df, strDB, parentDB):
    print(df.iloc[1, 0])
    db = strDB(html=parentDB, total=df.iloc[1, 1], euipertotal=df.iloc[1, 2], euipercondition=df.iloc[1, 3])
    db.save()


def process_html(html, dest):
    case = ProcessHtml(file=html)
    db = case.extract_html()
    # print (db["Unmet"])
    # register_df(db["Area"],area)
    case.export_all(dest)
    return db

project/templates/basic_info.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bar.css' %}" />

	<h2>{{object.project}} v_{{object.version}}</h2>
	<div class="navbar navbar-inverse" role="navigation">
        <div class="navbar-inner">
	        <ul class="nav navbar-nav">
                <li><a href="{% url 'project:detail' object.pk %}">Summary</a></li>
				<li><a href="{% url 'project:basic' object.pk %}">Basic info</a></li>
	        	<li><a href="{% url 'project:heat' object.pk %}">Heat balance</a></li>
				<li><a href="{% url 'project:time' object.pk %}">Time series</a></li>
			</ul>
		</div>
	</div>

    <h4>Basic information</h4>
        <div class="row">
		<div class="col-md-4" id="hbar">Area schedule[m2]</div>
		<div class="col-md-4" id="hbar4">WWR[%]</div>
		<div class="col-md-4" id="hbar5">Window area[m2]</div>
	    </div>
	    <div class="row">
		<div class="col-md-4" id="hbar1">Lighting Power Density[W/m2]</div>
		<div class="col-md-4" id="hbar2">People Density[m2/person]</div>
		<div class="col-md-4" id="hbar3">Small Power[W/m2]</div>
	    </div>
    </div>

<script src="{% static 'vendor/js/d3.js' %}"></script>
<script src="{% static 'vendor/js/jquery-2.2.3.min.js' %}"></script>
<script src="{% static 'js/hbar.js' %}"></script>


<script type="text/javascript">
    renderAll("{{object.loc.zone}}");

</script>

{% endblock %}

project/templates/heat_balance.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}

	<h2>{{object.project}} v_{{object.version}}</h2>
	<div class="navbar navbar-inverse" role="navigation">
        <div class="navbar-inner">
	        <ul class="nav navbar-nav">
                <li><a href="{% url 'project:detail' object.pk %}">Summary</a></li>
				<li><a href="{% url 'project:basic' object.pk %}">Basic info</a></li>
	        	<li><a href="{% url 'project:heat' object.pk %}">Heat balance</a></li>
				<li><a href="{% url 'upload' %}">Time series</a></li>
			</ul>
		</div>
	</div>

    <h4>Heat Gain for each room top 50</h4>
        <div class="row">
		<svg width="1200" height="600"></svg>
	    </div>
    </div>

<script src="{% static 'vendor/js/jquery-2.2.3.min.js' %}"></script>
<script src="//d3js.org/d3.v4.min.js"></script>
<script src="{% static 'js/stackbar.js' %}"></script>


<script type="text/javascript">
	readcsv("{{object.loc.heatbal}}");
</script>

{% endblock %}

project/templates/model_form_upload.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>
    </head>

    <body>
	{% block content %}
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button type="submit">Upload</button>
		</form>
	{% endblock %}
	</body>
</html>

project/templates/project_detail.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load humanize %}

	<h2>{{object.project}} v_{{object.version}}</h2>
	<div class="navbar navbar-inverse" role="navigation">
        <div class="navbar-inner">
	        <ul class="nav navbar-nav">
                <li><a href="{% url 'project:detail' object.pk %}">Summary</a></li>
				<li><a href="{% url 'project:basic' object.pk %}">Basic info</a></li>
	        	<li><a href="{% url 'project:heat' object.pk %}">Heat balance</a></li>
				<li><a href="{% url 'project:time' object.pk %}">Time series</a></li>
                <li><a href="{% url 'project:download' object.pk %}">Download</a></li>
			</ul>
		</div>
	</div>
	
    <div class="row">
        <div class="col-md-6" id="info">

            <table class="table">
                <thead>
                    <tr>
                        <th>Energy Conservation Measures</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ecm in object.ecms.all %}
                    <tr>
                        <td><a href="{% url 'ecm:detail' ecm.pk %}">{{ecm.name}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Area[m2]</th>
                        <th>Energy consumption[kWh]</th>
                        <th>EUI[kWh/m2]</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Total</th>
                        <td>{{object.area.total_area|floatformat:"0"|intcomma}}</td>
                        <td>{{object.energy.total|floatformat:"0"|intcomma}}</td>
                        <td>{{object.energy.euipertotal|floatformat:"0"|intcomma}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Conditioned area</th>
                        <td>{{object.area.condition_area|floatformat:"0"|intcomma}}</td>
                        <td> - </td>
                        <td>{{object.energy.euipercondition|floatformat:"0"|intcomma}}</td>
                    </tr>
                </tbody>
            </table>

            <table class="table">
                <thead>
                    <tr>
                        <th>WWR[%]</th>
                        <th>Total</th>
                        <th>North</th>
                        <th>East</th>
                        <th>South</th>
                        <th>West</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Above ground</th>
                        <td>{{object.wwr.total|floatformat:"1"}}</td>
                        <td>{{object.wwr.north|floatformat:"1"}}</td>
                        <td>{{object.wwr.east|floatformat:"1"}}</td>
                        <td>{{object.wwr.south|floatformat:"1"}}</td>
                        <td>{{object.wwr.west|floatformat:"1"}}</td>
                    </tr>
                </tbody>
            </table>

            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>heating period</th>
                        <th>cooling period</th>
                        <th>ASHRAE55-2004</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Unmet hour[h]</th>
                        <td>{{object.unmet.heating|floatformat:"0"}}</td>
                        <td>{{object.unmet.cooling|floatformat:"0"}}</td>
                        <td>{{object.unmet.ashrae|floatformat:"0"|intcomma}}</td>
                    </tr>
                </tbody>
            </table>


	    </div>

		<div class="col-md-6" id="pie">
            <h4>Energy Breakdown</h4>
        </div>
    </div>

<script src="{% static 'vendor/js/d3.js' %}"></script>
<script src="{% static 'js/pie.js' %}"></script>
<script src="{% static 'vendor/js/jquery-2.2.3.min.js' %}"></script>


<script type="text/javascript">
    readcsv("{{object.loc.energy}}",600,450,200,100);
</script>

{% endblock %}

project/templates/project_list.html
{% extends "base.html" %}
{% load humanize %}
{% load el_pagination_tags %}
{% load render_table from django_tables2 %}
{% block content %}

<h1>Project</h1>
<ul>
{#{% render_table object_list %}#}

<table class="table">
<thead>
	<tr>
		<th>Project</th>
		<th>Version</th>
		<th>Program</th>
		<th>Location</th>
        <th>Area[m2]</th>
        <th>EUI[kWh/m2]</th>
        <th>Unmet hour[h]</th>
		<th>Green certificate</th>
		<th>User</th>
	</tr>
</thead>
<tbody>
{# % paginate object_list % #}
{% for project in object_list %}
	<tr>
		<td><a href="{% url 'project:group' pk=project.project %}">{{project.project}}</a></td>
		<td><a href="{% url 'project:detail' project.pk %}">{{project.version}}</a></td>
		<td>{{project.program}}</a></td>
		<td>{{project.location}}</td>
        <td>{{project.area.total_area|floatformat:"0"|intcomma }}</td>
        <td>{{project.energy.euipertotal|floatformat:"0"}}</td>
        <td>{{project.unmet.heating|add:project.unmet.cooling}}</td>
		<td>{{project.certificate}}</td>
		<td>{{project.user}}</td>
	</tr>
</tbody>
{% empty %}
    <li>No projects yet.</li>
{% endfor %}
</ul>

{% endblock %}

project/templates/report.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bar.css' %}" />

	<h2>{{object.project}}</h2>
	<div class="navbar navbar-inverse" role="navigation">
        <div class="navbar-inner">
	        <ul class="nav navbar-nav">
                <li><a href="{% url 'project:detail' object.pk %}">Summary</a></li>
				<li><a href="{% url 'project:basic' object.pk %}">Basic info</a></li>
	        	<li><a href="{% url 'project:heat' object.pk %}">Heat balance</a></li>
				<li><a href="{% url 'project:time' object.pk %}">Time series</a></li>
			</ul>
		</div>
	</div>

<script src="{% static 'vendor/js/d3.js' %}"></script>
<script src="{% static 'vendor/js/jquery-2.2.3.min.js' %}"></script>
<script src="{% static 'js/hbar.js' %}"></script>


<script type="text/javascript">
    renderAll("{{zone}}");

</script>

{% endblock %}

project/templates/timeseries.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bar.css' %}" />

	<h2>{{object.project}}</h2>
	<div class="navbar navbar-inverse" role="navigation">
        <div class="navbar-inner">
	        <ul class="nav navbar-nav">
                <li><a href="{% url 'project:detail' object.pk %}">Summary</a></li>
				<li><a href="{% url 'project:basic' object.pk %}">Basic info</a></li>
	        	<li><a href="{% url 'project:heat' object.pk %}">Heat balance</a></li>
				<li><a href="{% url 'project:time' object.pk %}">Time series</a></li>
			</ul>
		</div>
	</div>

    <h2>Under Construction</h2>


<script src="{% static 'vendor/js/d3.js' %}"></script>
<script src="{% static 'vendor/js/jquery-2.2.3.min.js' %}"></script>

{% endblock %}