EnergyPlus/urls.py
from django.conf.urls import url,include
from rest_framework import routers
from django.contrib import admin
from heatBalance import views
from project.views import model_form_upload,basic,helpView,UploadView,form_wizard_view,ProjectAutocomplete

#router=routers.DefaultRouter()
#router.register(r'heat',views.heatBalViewSet)

urlpatterns = [
    #url(r'^', include(router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^upload/$',UploadView.as_view(),name='upload'),
    url(r'^wizard/$',form_wizard_view,name="form_wizard_view"),
    url(r'^project/',include('project.urls')),
    url(r'^help/$',helpView.as_view(),name='help'),
    url(r'^ecm/',include('ecm.urls')),
    url(r'^project-autocomplete/$',ProjectAutocomplete.as_view(),name='project-autocomplete')
    #url(r'^project/$',ListView.as_view(),name='project'),
    #url(r'^project/(?P<pk>\d+)/$',DetailView.as_view(),name='detail'),
    #url(r'^project/(?P<pk>\d+)/basic$',basic.as_view(),name='basic'),
]

ecm/urls.py
from django.conf.urls import url,include
from rest_framework import routers
from django.contrib import admin
from heatBalance import views
from .views import ListView,DetailView

app_name="ecm"
urlpatterns = [
    url(r'^$', ListView.as_view(),name='index'),
    url(r'^(?P<pk>\d+)/$', DetailView.as_view(),name='detail'),
]

project/urls.py
from django.conf.urls import url,include
from django_filters.views import FilterView
from .filters import ProjectFilter
from rest_framework import routers
from django.contrib import admin
from heatBalance import views
from .views import model_form_upload,ListView,DetailView,basic,ProjectView,heatView,reportView,timeView,download_csv

app_name="project"
urlpatterns = [
    url(r'^$', ListView.as_view(),name='index'),
    url(r'^search/$', FilterView.as_view(filterset_class=ProjectFilter,template_name='search.html'),name='search'),
    url(r'^(?P<pk>\d+)/$',DetailView.as_view(),name='detail'),
    url(r'^(?P<pk>\d+)/basic$',basic.as_view(),name='basic'),
    url(r'^(?P<pk>\d+)/heat$',heatView.as_view(),name='heat'),
    url(r'^(?P<pk>\d+)/time$',timeView.as_view(),name='time'),
    url(r'^(?P<pk>[\w-]+)/$',ProjectView.as_view(),name='group'),
    url(r'^(?P<pk>\d+)/download$',download_csv,name='download'),
    url(r'^(?P<pk>[\w-]+)/report$',reportView.as_view(),name='report'),
]

ecm/models.py
from django.db import models

# Create your models here.
class ecm(models.Model):
	name = models.CharField(max_length=50, blank=True)
	TARGET_CHOICES = (
		('Heating', 'Heating'),
		('Cooling', 'Cooling'),
        ('Fan', 'Fan'),
		('Lighting', 'Lighting'),
		('Equipment', 'Equipment'),
        ('Renewable','Renewable Energy'),
        ('Hot Water','Hot Water System'),
		('Others', 'Others'),
	)
	target=models.CharField(max_length=20, choices=TARGET_CHOICES, default='Others')
	description = models.TextField(blank=True)
	link=models.URLField(blank=True)

	def __str__(self):
		return self.name

ecm/forms.py
from django import forms
from ecm.models import ecm
from django.forms import widgets


class DocumentForm(forms.ModelForm):
    class Meta:
        model = ecm
        fields = ['name', 'target', 'description', 'link']

ecm/views.py
from django.shortcuts import render
from ecm.forms import DocumentForm
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from ecm.models import ecm

# Create your views here.
class ListView(ListView):
    model = ecm
    template_name = 'ecm_list.html'

class DetailView(DetailView):
    model = ecm
    template_name = 'ecm_detail.html'

class FormView(FormView):
    form_class=DocumentForm
    template_name='model_form_upload.html'
    success_url='/ecm/'

ecm/templates/base.html
{% load staticfiles %}
<html>
	<head>
		<title>Energy Conservation Measures</title>
		<link href="{% static 'vendor/css/bootstrap.css' %}" rel="stylesheet" media="screen" />
		{% block css %}
		{% endblock %}
	</head>
	<body>
	<div class = "container">
	<h2>Energy Conservation Measures</h2>
		<div class="navbar navbar-inverse" role="navigation">
	        <div class="navbar-inner">
	        	<ul class="nav navbar-nav">
	        		<li><a href="{% url 'project:index' %}">ECMs</a></li>
					<li><a href="{% url 'upload' %}">Register</a></li>
				</ul>
			</div>
		</div>
			{% block content %}
				{{content}}
			{% endblock %}

		<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
			<p class="navbar-text navbar-right">Footer</p>
		</nav>
	</div>

		<script src="{% static 'vendor/js/jquery-2.2.3.min.js' %}"></script>
		<script src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
		{% block js %}
		{% endblock %}

	</body>
</html>

ecm/templates/ecm_detail.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/glass.css' %}" />

	<h2>{{object.name}} </h2>
	<h4>Target:{{object.target}}</h4>
    <h4>Description:{{object.description}}</h4>

<div class="container">
    <div class="row">
    <h4>Glass performance</h4>
        <div class="col-md-12" id="glass-scatter">
        </div>
        <div class="col-md-12" id="legend">
        </div>
    </div>
</div>
<script src="{% static 'vendor/js/d3_v4.js' %}"></script>
<script src="{% static 'js/glassScatter.js' %}"></script>
<script src="{% static 'vendor/js/jquery-2.2.3.min.js' %}"></script>

<script type="text/javascript">
    createGraph("{% static 'csv/glass.csv' %}");
</script>

{% endblock %}

ecm/templates/ecm_list.html
{% extends "base.html" %}
{% block content %}

<h1>ECM List</h1>
<ul>

<table class="table">
<thead>
	<tr>
		<th>Measures</th>
		<th>Target</th>
		<th>Description</th>
		<th>Link</th>

	</tr>
</thead>
<tbody>
{% for project in object_list %}
	<tr>
		<td>{{project.name}}</td>
		<td>{{project.target}}</td>
		<td>{{project.description}}</td>
		<td>{{project.link}}</td>
	</tr>
</tbody>
{% empty %}
    <li>No projects yet.</li>
{% endfor %}
</ul>
{% endblock %}

ecm/templates/model_form_upload.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>
    </head>

    <body>
	{% block content %}
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button type="submit">Upload</button>
		</form>
	{% endblock %}
	</body>
</html>